TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB_INSTALLS += $(TOP)/GSpiSup/devGSpi.db
DB_INSTALLS += $(TOP)/GSpiSup/devGSpi.proto

#=======================================
include $(TOP)/configure/RULES
